"""AutoCAD integration registry: the bundled NETLOAD plugin is a first-class add-in (install/
update copies DLL + version.json into the runtime dir; the COM driver NETLOADs it on attach and
stays the fallback). Locked-DLL updates are STAGED, not failed."""
import sys
from pathlib import Path

import pytest

from trackball_daemon import integrations
from trackball_daemon.config import Config


def test_autocad_is_an_addin():
    assert "autocad" in integrations.ADDIN_KEYS
    # the bundled manifest is generated by the plugin's Release build
    assert integrations.bundled_addin_version("autocad") is not None


def test_install_copies_plugin_and_manifest(isolated_config, monkeypatch):
    cfg = Config().load()
    monkeypatch.setattr(integrations, "detect_autocad", lambda: r"C:\fake\acad.exe")
    appdef = integrations.APPS_BY_KEY["autocad"]
    ok, msg = integrations.install(appdef, cfg)
    assert ok is True
    dst = integrations._acad_runtime_plugin_dir()
    assert (dst / "TrackballNavAcad.dll").exists()
    assert (dst / "version.json").exists()
    bundled = integrations.bundled_addin_version("autocad")
    assert integrations.installed_addin_version("autocad") == bundled
    assert integrations.update_available("autocad") is False
    ac = cfg.data["apps"]["autocad"]
    assert ac["enabled"] is True and ac["installed"] is True
    assert ac["addin_version"] == bundled
    assert "TBNAV" in msg


def test_locked_dll_stages_the_update(isolated_config, monkeypatch):
    cfg = Config().load()
    monkeypatch.setattr(integrations, "detect_autocad", lambda: r"C:\fake\acad.exe")

    def locked_copy(src, dst):
        raise OSError("locked by acad.exe")

    monkeypatch.setattr(integrations.shutil, "copy2", locked_copy)
    appdef = integrations.APPS_BY_KEY["autocad"]
    ok, msg = integrations.install(appdef, cfg)
    assert ok is True                                    # staged, not failed
    assert "STAGED" in msg and "next time" in msg.lower()
    assert integrations.installed_addin_version("autocad") is None


def test_update_available_via_manifest(isolated_config, monkeypatch):
    monkeypatch.setattr(integrations, "detect_autocad", lambda: r"C:\fake\acad.exe")
    dst = integrations._acad_runtime_plugin_dir()
    dst.mkdir(parents=True, exist_ok=True)
    (dst / "version.json").write_text('{"version": "0.0.1"}', encoding="utf-8")
    assert integrations.installed_addin_version("autocad") == "0.0.1"
    assert integrations.update_available("autocad") is True


def test_auto_update_recopies_stale_plugin(isolated_config, monkeypatch):
    cfg = Config().load()
    monkeypatch.setattr(integrations, "detect_autocad", lambda: r"C:\fake\acad.exe")
    dst = integrations._acad_runtime_plugin_dir()
    dst.mkdir(parents=True, exist_ok=True)
    (dst / "version.json").write_text('{"version": "0.0.1"}', encoding="utf-8")
    updated = integrations.auto_update(cfg)
    assert ("autocad", "0.0.1", integrations.bundled_addin_version("autocad")) in updated
    assert integrations.update_available("autocad") is False


def test_install_fails_when_autocad_absent(isolated_config, monkeypatch):
    cfg = Config().load()
    monkeypatch.setattr(integrations, "detect_autocad", lambda: None)
    appdef = integrations.APPS_BY_KEY["autocad"]
    ok, msg = integrations.install(appdef, cfg)
    assert ok is False
    assert "not found" in msg.lower()
    assert cfg.data["apps"]["autocad"]["enabled"] is False


def test_autocad_in_default_config(isolated_config):
    # config.DEFAULTS["apps"] must include the autocad app (deep-merge adds it to old configs too).
    cfg = Config().load()
    assert "autocad" in cfg.data["apps"]
    ac = cfg.data["apps"]["autocad"]
    assert ac["enabled"] is False and ac["installed"] is False
    assert ac["bindings"]["scheme"]["orbit_pivot"] == "default"   # shared _app() shape


def test_autocad_plugin_consumes_selection_override_and_all_generic_pivots():
    source = (Path(__file__).parents[1] / "plugin_src" / "autocad" /
              "TrackballNavAcad" / "Plugin.cs").read_text(encoding="utf-8")
    assert 'TryGetProperty("selection_overrides_pivot"' in source
    assert "CaptureSelectionCenter(doc)" in source
    assert 'case "origin": return Point3d.Origin;' in source
    assert 'case "object":' in source and "CaptureDrawingCenter()" in source


@pytest.mark.skipif(sys.platform != "win32", reason="status detection is Windows-only")
def test_status_line_reflects_detection(monkeypatch):
    appdef = integrations.APPS_BY_KEY["autocad"]
    monkeypatch.setattr(appdef, "detect", lambda: r"C:\fake\acad.exe")
    assert "detected" in integrations.status_line(appdef).lower()
    monkeypatch.setattr(appdef, "detect", lambda: None)
    assert integrations.status_line(appdef) == "not detected"
