"""AutoCAD integration registry and bundled NETLOAD-plugin installation behavior.

The daemon's COM loader delivers the in-process plugin; navigation itself uses the broker. Only an
existing DLL blocked by a Windows sharing/lock violation is reported as a staged update.
"""
from pathlib import Path

from trackball_daemon import integrations
from trackball_daemon.config import Config


def test_autocad_is_an_addin():
    assert "autocad" in integrations.ADDIN_KEYS
    # the bundled manifest is generated by the plugin's Release build
    assert integrations.bundled_addin_version("autocad") is not None


def test_install_copies_plugin_and_manifest(isolated_config, monkeypatch):
    cfg = Config().load()
    monkeypatch.setattr(integrations, "detect_autocad", lambda: r"C:\fake\acad.exe")
    appdef = integrations.APPS_BY_KEY["autocad"]
    ok, msg = integrations.install(appdef, cfg)
    assert ok is True
    dst = integrations._acad_runtime_plugin_dir()
    assert (dst / "TrackballNavAcad.dll").exists()
    assert (dst / "version.json").exists()
    bundled = integrations.bundled_addin_version("autocad")
    assert integrations.installed_addin_version("autocad") == bundled
    assert integrations.update_available("autocad") is False
    ac = cfg.snapshot().app_operational["autocad"]
    assert ac["enabled"] is True and ac["installed"] is True
    assert ac["addin_version"] == bundled
    assert "TBNAV" in msg


def test_locked_dll_stages_the_update(isolated_config, monkeypatch):
    cfg = Config().load()
    monkeypatch.setattr(integrations, "detect_autocad", lambda: r"C:\fake\acad.exe")
    runtime = integrations._acad_runtime_plugin_dir()
    runtime.mkdir(parents=True, exist_ok=True)
    (runtime / "TrackballNavAcad.dll").write_bytes(b"loaded old plugin")
    (runtime / "version.json").write_text('{"version": "0.0.1"}', encoding="utf-8")

    def locked_copy(src, dst):
        exc = PermissionError("locked by acad.exe")
        exc.winerror = 32
        raise exc

    monkeypatch.setattr(integrations.shutil, "copy2", locked_copy)
    appdef = integrations.APPS_BY_KEY["autocad"]
    ok, msg = integrations.install(appdef, cfg)
    assert ok is True                                    # staged, not failed
    assert "STAGED" in msg and "next time" in msg.lower()
    assert integrations.installed_addin_version("autocad") == "0.0.1"
    assert cfg.snapshot().app_operational["autocad"]["installed"] is True
    assert integrations.auto_update(cfg) == []       # do not claim the locked runtime copy changed


def test_existing_plugin_with_non_lock_write_failure_is_not_staged(isolated_config, monkeypatch):
    cfg = Config().load()
    monkeypatch.setattr(integrations, "detect_autocad", lambda: r"C:\fake\acad.exe")
    runtime = integrations._acad_runtime_plugin_dir()
    runtime.mkdir(parents=True, exist_ok=True)
    (runtime / "TrackballNavAcad.dll").write_bytes(b"old plugin")

    def denied_copy(src, dst):
        exc = PermissionError("directory access denied")
        exc.winerror = 5
        raise exc

    monkeypatch.setattr(integrations.shutil, "copy2", denied_copy)

    ok, msg = integrations.install(integrations.APPS_BY_KEY["autocad"], cfg)

    assert ok is False
    assert "could not copy" in msg.lower() and "access denied" in msg.lower()
    assert cfg.snapshot().app_operational["autocad"]["installed"] is False


def test_first_install_copy_failure_is_not_reported_as_staged(isolated_config, monkeypatch):
    cfg = Config().load()
    monkeypatch.setattr(integrations, "detect_autocad", lambda: r"C:\fake\acad.exe")

    def denied_copy(src, dst):
        raise OSError("access denied")

    monkeypatch.setattr(integrations.shutil, "copy2", denied_copy)

    ok, msg = integrations.install(integrations.APPS_BY_KEY["autocad"], cfg)

    assert ok is False
    assert "could not copy" in msg.lower() and "access denied" in msg.lower()
    assert cfg.snapshot().app_operational["autocad"]["installed"] is False
    assert cfg.snapshot().app_operational["autocad"]["enabled"] is False


def test_missing_bundled_dll_fails_honestly(isolated_config, monkeypatch):
    cfg = Config().load()
    monkeypatch.setattr(integrations, "detect_autocad", lambda: r"C:\fake\acad.exe")
    original = integrations._bundled_addin

    def missing_dll(*parts):
        if parts[-1] == "TrackballNavAcad.dll":
            return isolated_config / "missing-TrackballNavAcad.dll"
        return original(*parts)

    monkeypatch.setattr(integrations, "_bundled_addin", missing_dll)

    ok, msg = integrations.install(integrations.APPS_BY_KEY["autocad"], cfg)

    assert ok is False
    assert "missing from this build" in msg.lower()
    assert cfg.snapshot().app_operational["autocad"]["installed"] is False


def test_update_available_via_manifest(isolated_config, monkeypatch):
    monkeypatch.setattr(integrations, "detect_autocad", lambda: r"C:\fake\acad.exe")
    dst = integrations._acad_runtime_plugin_dir()
    dst.mkdir(parents=True, exist_ok=True)
    (dst / "version.json").write_text('{"version": "0.0.1"}', encoding="utf-8")
    assert integrations.installed_addin_version("autocad") == "0.0.1"
    assert integrations.update_available("autocad") is True


def test_auto_update_recopies_stale_plugin(isolated_config, monkeypatch):
    cfg = Config().load()
    monkeypatch.setattr(integrations, "detect_autocad", lambda: r"C:\fake\acad.exe")
    dst = integrations._acad_runtime_plugin_dir()
    dst.mkdir(parents=True, exist_ok=True)
    (dst / "version.json").write_text('{"version": "0.0.1"}', encoding="utf-8")
    updated = integrations.auto_update(cfg)
    assert ("autocad", "0.0.1", integrations.bundled_addin_version("autocad")) in updated
    assert integrations.update_available("autocad") is False


def test_install_fails_when_autocad_absent(isolated_config, monkeypatch):
    cfg = Config().load()
    monkeypatch.setattr(integrations, "detect_autocad", lambda: None)
    appdef = integrations.APPS_BY_KEY["autocad"]
    ok, msg = integrations.install(appdef, cfg)
    assert ok is False
    assert "not found" in msg.lower()
    assert cfg.snapshot().app_operational["autocad"]["enabled"] is False


def test_autocad_in_default_config(isolated_config):
    # config.DEFAULTS["apps"] must include the autocad app (deep-merge adds it to old configs too).
    cfg = Config().load()
    assert "autocad" in cfg.snapshot().app_operational
    ac = cfg.snapshot().app_operational["autocad"]
    assert ac["enabled"] is False and ac["installed"] is False
    assert cfg.snapshot().app_value("autocad", "navigation.orbit.pivot") == "screen_center"


def test_autocad_plugin_consumes_advanced_settings_and_all_generic_pivots():
    source = (Path(__file__).parents[1] / "plugin_src" / "autocad" /
              "TrackballNavAcad" / "Plugin.cs").read_text(encoding="utf-8")
    assert 'TryGetProperty("selection_overrides_pivot"' in source
    assert 'TryGetProperty("level_horizon_on_entry"' in source
    assert 'TryGetProperty("zoom_style"' in source
    assert 'TryGetProperty("orbit_hold_sec"' in source
    assert 'TryGetProperty("zoom_hold_sec"' in source
    assert "CaptureSelectionCenter(doc)" in source
    assert 'case "origin": point = Point3d.Origin;' in source
    assert 'case "object":' in source and "CaptureDrawingCenter()" in source
    assert "NavMath.ReprojectScreenSample(_ptrPoint, camBefore, _cam)" in source
    assert "_ptrOnEntity = false;" in source
    assert "if (!GetCursorPos(out _ptrScreen))" in source
    assert "_ptrScreenValid = true;" in source
    assert "!GetCursorPos(out var currentScreen)" in source
    assert "currentScreen.X != _ptrScreen.X || currentScreen.Y != _ptrScreen.Y" in source
    assert "cached sample no longer owns the current cursor pixel" in source
    assert "if (hasPan || (hasOrbit && idleMs > orbitHoldMs))" in source
    assert "if (hasOrbit)                                  // next cursor zoom re-captures" in source
    assert "NavMath.IsModelView(doc.Database.TileMode, vpn)" in source
    assert "EnterFallback(FallbackReason.PaperSpace, doc)" in source
    assert "doc.Editor.CurrentViewportObjectId" in source
    assert "_gsViewportId != viewportId" in source
    assert "return GsApplyResult.Deferred" in source
    assert "_levelPending |= levelOnEntry" in source
    owner_gate = source[source.index("bool isTiled = doc.Database.TileMode"):
                        source.index("if (_gsActive &&", source.index(
                            "bool isTiled = doc.Database.TileMode"))]
    assert "if (!isTiled)" in owner_gate
    assert "CurrentViewportObjectId" in owner_gate
    assert "IsTiled2DWireframe(doc, vpn)" in source
    assert "PersistTiled2DShadowCamera(doc, vpn, cam)" in source
    assert "PersistFloating2DShadowCamera(doc, viewportId, cam)" in source
    assert "floating.UpdateDisplay()" in source
    assert "if (isTiled)" in source
    assert "_fallbackReason != FallbackReason.PaperSpace" in source
    assert "model-camera navigation is paused" in source
    assert "configured/selection pivots" in source
    assert "To Cursor/Object anchoring" in source
    assert "Dolly are unavailable" in source
    frame_parser = source[source.index("void HandleFrame"):source.index("// --- UI-thread timer")]
    assert "_horizonFixed = fixedHorizon" in frame_parser
    assert "_levelPending = true" in frame_parser


def test_autocad_plugin_discovers_the_daemon_broker_port():
    root = Path(__file__).parents[1] / "plugin_src" / "autocad" / "TrackballNavAcad"
    plugin = (root / "Plugin.cs").read_text(encoding="utf-8")
    resolver = (root / "BrokerConfig.cs").read_text(encoding="utf-8")
    assert "BrokerConfig.ResolvePort()" in plugin
    assert "const int BrokerPort" not in plugin
    assert '"TrackballDaemon", "bridge.json"' in resolver
    assert "port >= 1 && port <= 65535" in resolver
    assert "return DefaultPort" in resolver
